### ISSUE TITLE
findsecbugs-plugin resolution is broken in SBT 1.3.x

### ISSUE THREAD

**Issue by nigredo-tori** [code-star/sbt-findsecbugs#33]
This code assumes that the artifacts are resolved via Ivy - which is not the case in SBT 1.3.x:

https://github.com/code-star/sbt-findsecbugs/blob/f1d6bc70e93743d923a314d67647f6150feeedc4/src/main/scala/nl/codestar/sbtfindsecbugs/FindSecBugs.scala#L52

As a result, no checks are actually run (since SpotBugs ignores missing plugin JARs).

Instead of hardcoding the path for the JAR, we should just use the `UpdateReport` we can get from `update`.

**Comment by jqno** [comment]
Thanks! I've pushed a new release.
