### ISSUE TITLE
Allow configuring the forked JVM

### ISSUE THREAD

**Issue by nigredo-tori** [code-star/sbt-findsecbugs#35]
At the moment, all the JVM options are [hardcoded](https://github.com/code-star/sbt-findsecbugs/blob/3a951913eee914a9665487b481fd55e9ac49d3af/src/main/scala/nl/codestar/sbtfindsecbugs/FindSecBugs.scala#L78). This is bad for multiple reasons; the one that brought me here is that there is no way to increase the amount of memory for the spawned JVM. So, if for a large project the plugin runs out of memory, there is no way to make it work other than splitting the project.

I suggest we provide a `findSecBugs / forkOptions` setting with all the standard [wiring](https://github.com/sbt/sbt/blob/fb17606ac92e607a39fc4c5afa5adcfef00c6370/main/src/main/scala/sbt/Defaults.scala#L984-L996), and move all the JVM options there.

**Comment by jqno** [comment]
I've created a new release with the code from your PR. Thanks!
