### ISSUE TITLE
Hardcoded directory :gasp

### ISSUE THREAD

**Issue by Hayena** [code-star/sbt-findsecbugs#6]
`lazy val pluginList = s"${Path.userHome.absolutePath}/.ivy2/cache/com.h3xstream.findsecbugs/findsecbugs-plugin/jars/findsecbugs-plugin-1.4.5.jar"`

should be 

`lazy val pluginList = s"${ivy.cache-directory}/com.h3xstream.findsecbugs/findsecbugs-plugin/jars/findsecbugs-plugin-1.4.5.jar"`

ivy.cache-directory

**Comment by jqno** [comment]
I tried to do this, but `ivy.cache-directory` should be a valid Scala identifier. (This looks like a Maven variable maybe?) I couldn't quickly find a suitable equivalent quickly.

**Comment by Hayena** [comment]
Hmm, I will have a look this weekend.

**Comment by jqno** [comment]
No rush ☺.

**Comment by jqno** [comment]
@Hayena Please take a look at #9 . Is this ok?

**Comment by Hayena** [comment]
👍
